version: "3"

services:

  networksandbox:
    image: k8s.gcr.io/pause

  eos1100d:
    privileged: true
    image: nixery.dev/shell/ffmpeg/gphoto2
    command:
    - sh
    - -c
    - |
      gphoto2 --stdout --capture-movie \
      | ffmpeg -i - -vcodec rawvideo -pix_fmt yuv420p -threads 0 -f v4l2 /dev/video9

  v4l2loopback:
    privileged: true
    image: alpine
    command: modprobe v4l2loopback video_nr=8,9 card_label=OBS,EOS1100D
    volumes:
    - /lib/modules:/lib/modules

  alsaloopback:
    privileged: true
    image: alpine
    command: modprobe snd-aloop index=9 id=Loopback pcm_substreams=1
    volumes:
    - /lib/modules:/lib/modules

  obs:
    privileged: true
    network_mode: "service:networksandbox"
    ipc: host
    build:
      context: obs-studio
      dockerfile: Dockerfile.${OBS_IMAGE_DISTRO-ubuntu}
    environment:
    - DISPLAY
    - HOME
    - USER
    - XAUTHORITY
    volumes:
    - /tmp/.X11-unix/:/tmp/.X11-unix/
    - $HOME/.config/obs-studio:$HOME/.config/obs-studio
    - $HOME/.fonts/:$HOME/.fonts/
    - $XAUTHORITY:$XAUTHORITY:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - /etc/group:/etc/group:ro
    - /run/user/$UID/pulse/:/var/run/pulse/
    - ./data/:/data/
    - /usr/lib/x86_64-linux-gnu/:/local-libraries/:ro
    # Directory containing e.g. images, videos, etc. used in OBS scenes
    #- $HOME/Documents/streaming-assets:$HOME/Documents/streaming-assets
    command:
    - sh
    - -c
    - |
      chown ${UID:?please 'export UID'} $HOME/.config/obs-studio
      chown ${UID:?please 'export UID'} $HOME
      xset -dpms
      xset s off
      if [ -d /local-libraries ]; then
        cp -a /local-libraries/libnv* /usr/lib/x86_64-linux-gnu/
        cp -a /local-libraries/nvidia/current/* /usr/lib/x86_64-linux-gnu/
      fi
      mkdir -p $HOME/.config/obs-studio/plugins
      [ -d $HOME/.config/obs-studio/plugins/obs-linuxbrowser ] ||
        ln -sf /src/obs-linuxbrowser $HOME/.config/obs-studio/plugins/obs-linuxbrowser
      exec su $USER sh -c "exec obs"

  streamdeck:
    privileged: true
    network_mode: "service:networksandbox"
    build: streamdeck
    environment:
    - DISPLAY
    - HOME
    - USER
    - PATH=/scripts:/usr/local/bin:/usr/bin:/bin
    volumes:
    - /tmp/.X11-unix/:/tmp/.X11-unix/
    - $HOME/.config/streamdeck_ui:$HOME
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - /etc/group:/etc/group:ro
    - ./bin/:/scripts/:ro
    - ./data/:/data/
    - /home/jp/recordings/:/recordings/:ro
    working_dir: /data
    command:
    - sh
    - -c
    - |
      chown ${UID:?please 'export UID'} $HOME
      exec su -G input -G video $USER sh -c "exec streamdeck"

  countdown:
    image: python:3
    volumes:
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - ./bin:/usr/local/bin
    - ./data/:/data/
    working_dir: /data
    command:
    - sh
    - -c
    - |
      exec su $USER sh -c "exec countdown _"

